#!/usr/bin/env python3
"""Generate source-registry/CATALOGUE.md from validated records. Do not edit by hand."""
from __future__ import annotations
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from ii import sources as src  # noqa: E402

DISCLAIMER = (
    "> Motif maintains a community-curated registry of third-party interface libraries, design "
    "systems, component collections, tools and inspiration sources. Registry inclusion does not "
    "constitute endorsement, licence approval, security certification, accessibility "
    "certification or production approval. Every source and component must be evaluated for its "
    "intended project context. Motif records provenance and verification evidence, but "
    "maintainers and users remain responsible for final legal, security, accessibility and "
    "product decisions.")
PRIVACY = (
    "> Source Discovery is opt-in. Motif does not upload project code, private repository "
    "information, prompts, browsing history, credentials or environment data when contributing "
    "source records.")

SECTIONS = [
    ("Verified for direct reuse", lambda r: r["assurance"]["status"] == "verified-direct-reuse"),
    ("Verified but adaptation required", lambda r: r["assurance"]["status"] == "verified-adapt-before-use"),
    ("Pattern-reference sources", lambda r: r["assurance"]["status"] == "pattern-reference-only"),
    ("Inspiration-only sources", lambda r: r["classification"].get("registry_class") == "inspiration"),
    ("Competitors and adjacent tools", lambda r: r["classification"].get("registry_class") == "competitor"),
    ("Unreviewed candidates", lambda r: r["assurance"]["status"] == "seed-unreviewed"
        and r["classification"].get("registry_class") not in ("inspiration", "competitor")),
    ("Restricted sources", lambda r: r["assurance"]["status"] == "restricted"),
    ("Blocked sources", lambda r: r["assurance"]["status"] == "blocked"),
]


def main():
    recs = src.load_all()
    n, errs = src.validate()
    lines = ["# Motif source registry catalogue", "",
             "Generated by `tools/build_source_catalogue.py`. Do not edit by hand.", "",
             f"{len(recs)} sources. {DISCLAIMER}", "", PRIVACY, ""]
    for title, pred in SECTIONS:
        sel = [r for r in recs if pred(r)]
        if not sel:
            continue
        lines.append(f"## {title} ({len(sel)})")
        lines.append("")
        lines.append("| Name | Category | Frameworks | Reuse status | Licence | Last verified | Limitations |")
        lines.append("|---|---|---|---|---|---|---|")
        for r in sorted(sel, key=lambda x: x["id"]):
            cls = r["classification"]
            lines.append("| {name} | {cat} | {fw} | {status} | {lic} | {ver} | {lim} |".format(
                name=r["identity"]["name"], cat=cls.get("registry_category", ""),
                fw=",".join(cls.get("frameworks", [])) or "-",
                status=r["assurance"]["status"],
                lic=("verified " + r["licence"]["identifier"]) if r["licence"]["verified_from_primary_source"] else "unverified",
                ver=r["provenance"].get("last_verified") or "never",
                lim=(r["assurance"]["limitations"] or ["-"])[0]))
        lines.append("")
    (ROOT / "source-registry" / "CATALOGUE.md").write_text("\n".join(lines) + "\n")
    print(f"wrote source-registry/CATALOGUE.md ({len(recs)} sources, {len(errs)} schema errors)")


if __name__ == "__main__":
    main()
